### ISSUE TITLE
Watch doesn't scan prof.includes paths

### ISSUE THREAD

**Issue by kchmie** [christhefrog/pawnctl#1]
Adressing the comment found at `main.go:96` that reads:
```go
/*
Here's a really stupid workaround for fsnotify not supporting recursive watching.
Apparently it did suport it for windows, but since the maintainer didn't want to
write it for other backends, he removed it??

This solution also appears to trigger windows defender XD.

Also, with YSI installed, this function watches all it's directories which results
with hundreds entries added to the watcher. I don't know if it affects performance
much, but it definietly is worth consideration.
*/  
```
The problem is most propably this code found at `main.go:107`:
```go
filepath.WalkDir(v, func(path string, d fs.DirEntry, err error) error {
	if err == nil && d.IsDir() {
		watcher.Add(path)
	}
	return nil
})
```
It traverses all subdirectories of the paths listed in project config, which may cause windows defender to think its malware.
Apparently there are no cases of this happening elsewhere. It's weird but the cause of the problem definietly lies somewhere in watch implementation.

I've decided not to reference the function anywhere in the code (which causes the go compiler not to include it in the binary) to prevent windows defender for going crazy. It's not a solution of course, hence why a new method of watching should be found. Perhaps a different library or directly utilising `ReadDirectoryChangesW`.

**Comment by kchmie** [comment]
Managed to fix the initial problem in 2d27c0d.

I took a little glimpse at sampctl source code and found it using `filepath.Walk` instead of `filepath.WalkDir`. I implemented that in `pawnctl` and it somehow fixed the windows defender issue.

The only problem left regarding this issue is (`main.go:93`)
```go
// See christhefrog/pawnctl#1
color.Red.Printf("\nPlease note that for the time, watch only looks for changes in %s\\**.\n", parent)
color.Gray.Print("It means that other directories specified in profile.includes (ex. qawno\\include) aren't scanned.\n \n")
```
I'll leave it like that for now as it is actually the case in `sampctl` and noone has a problem with it. If it bothers anyone, feel free to reopen the issue and I'll be happy to help.

**Comment by christhefrog** [comment]
Closing. If it bothers anyone, feel free to reopen the issue and I'll be happy to help.

**Comment by kchmie** [comment]
Closing. If it bothers anyone, feel free to reopen the issue and I'll be happy to help.
